#
# DCC Repository Client - Defaults
#

 # TODO: see dcc-metadata-server for similar properites
###################################################################################################
# Profile Activation
###################################################################################################

# One of:
# - development
# - production

spring:
  profiles.active: development

###################################################################################################
# Common
###################################################################################################

---

###################################################################################################
# Development
###################################################################################################

# Spring
spring:
  profiles: development
   
# Gene MongoDB URI
geneMongoUri: "mongodb://localhost/dcc-genome"

# Repository MongoDB URI
repoMongoUri: "mongodb://localhost/dcc-repository"

# Elasticsearch URI
esUri: "es://localhost:9300"

# ID Service URL
identifierServiceUri: "https://localhost:8443"
   