#
# DCC Repository Client - Configuration
#
 
###################################################################################################
# Profile Activation
###################################################################################################

# One of:
# - development
# - production

spring:
  profiles.active: development

###################################################################################################
# Common
###################################################################################################

# Repository
repository:
  sources: PCAWG,AWS,COLLAB,TCGA,CGHUB
  steps: IMPORT,MERGE,INDEX
  indexAlias: icgc-repository

# Mail
mail:
  smtpServer: "***REMOVED***"
  recipients: "***REMOVED***"

---

###################################################################################################
# Development
###################################################################################################

# Spring
spring:
  profiles: development

# Repository
repository:
  esUri: es://localhost:9300
  mongoUri: mongodb://localhost/dcc-repository
  indexAlias: test-icgc-repository

# Imports
imports:
  mongoUri: mongodb://localhost/dcc-genome

# ID
id:
  serviceUrl: https://localhost:8443

# Mail
mail:
  enabled: false
