#
# DCC Repository Client - Defaults
#
 
###################################################################################################
# Profile Activation
###################################################################################################

# One of:
# - development
# - production

spring:
  profiles.active: development

###################################################################################################
# Common
###################################################################################################

# Empty
repository:
  mail: true
  sources: # All
  steps: # All

---

###################################################################################################
# Development
###################################################################################################

# Spring
spring:
  profiles: development

# Repository
repository:
  mail: false
  esUri: es://localhost:9300
  mongoUri: mongodb://localhost/dcc-repository

# Imports
imports:
  mongoUri: mongodb://localhost/dcc-genome

# ID
id:
  serviceUrl: https://localhost:8443

